version: 2.1
orbs:
  docker: circleci/docker@0.5.19
jobs:
  build:
    executor: docker/docker
    steps:
      - checkout
      - setup_remote_docker: 
         docker_layer_caching: true 
      - run: docker build -t sebastianneb/aws_deployer:latest .
  release:
    executor: docker/docker
    steps:
      - checkout
      - setup_remote_docker: 
         docker_layer_caching: true
      - run: docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
      - run: docker build -t sebastianneb/aws_deployer:$CIRCLE_TAG .
      - run: docker push sebastianneb/aws_deployer:$CIRCLE_TAG

workflows:
  version: 2
  test:
    jobs:
      - docker/hadolint
      - build
  tagged_release:
    jobs:
      - docker/hadolint:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - release:
          requires:
            - docker/hadolint
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
