version: 2.1
orbs:
  docker: circleci/docker@0.5.19
jobs:
  build:
    executor: docker/docker
    steps:
      - checkout
      - setup_remote_docker: 
         docker_layer_caching: true
      - run: export BUILD_TIME=$(date)
      - run: >
          docker build -t sebastianneb/aws_deployer:latest
          --build-arg BUILD_TIME=$BUILD_TIME
          --build-arg REPOSITORY_URL=$CIRCLE_REPOSITORY_URL
          --build-arg REVISION=$CIRCLE_SHA1
          --build-arg VERSION=v0.0.0-SNAPSHOT .
  release:
    executor: docker/docker
    steps:
      - checkout
      - setup_remote_docker: 
         docker_layer_caching: true
      - run: docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
      - run: export BUILD_TIME=$(date)
      - run: >
          docker build -t sebastianneb/aws_deployer:latest
          --build-arg BUILD_TIME=$BUILD_TIME
          --build-arg REPOSITORY_URL=$CIRCLE_REPOSITORY_URL
          --build-arg REVISION=$CIRCLE_SHA1
          --build-arg VERSION=$CIRCLE_TAG .
      - run: docker tag sebastianneb/aws_deployer:$CIRCLE_TAG sebastianneb/aws_deployer:latest
      - run: docker push sebastianneb/aws_deployer:$CIRCLE_TAG
      - run: docker push sebastianneb/aws_deployer:latest

workflows:
  version: 2
  test:
    jobs:
      - docker/hadolint
      - build
  tagged_release:
    jobs:
      - docker/hadolint:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - release:
          requires:
            - docker/hadolint
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
